package main

type l6 struct {
	str   string
	verse string
}

var list666 []l6 = []l6{
	{"A SATANIC MARK", ""},
	{"SATAN'S SEAL", "Rev 13:16"},
	{"A SATANIC PLAN", ""},
	{"RECEIVE A MARK", ""},
	{"CHOICE OF DOOM", ""},
	{"FOREHEAD SIGN", "Rev 13:16"},
	{"THE HAND OR HEAD", "Rev 13:16"},
	{"EDEN TEMPTED", ""},
	{"PEOPLE SIN", ""},
	{"DEVIL'S HEIR", ""},
	{"HUMANITY", ""},
	{"SON OF SIN", ""},
	{"WICKED WILL", ""},
	{"STUBBORN", ""},
	{"SCORNERS", ""},
	{"LUSTFUL", "1 Jn 2:16-17"},
	{"TREACHERIES", "Isa 33:1"},
	{"CORRUPT", "Gen 6:11-12"},
	{"FLOOD OF NOAH", ""},
	{"COMPUTER", "The Greek word, \"psephizo,\" translated \"count\" in Rev 13:18 is defined as to compute, calculate"},
	{"TERMINALS", ""},
	{"BIO-IMPLANT", ""},
	{"LUCIFER HELL", ""},
	{"HELL: TWICE DEAD", "Rom 3:23; Jude 11-13; Rev 2:11, 20:6, 14, 21:8"},
	{"HELL: A REAL PLACE", ""},
	{"HELL BURNS", "Lk 16:23-25"},
	{"SET ON FIRE", ""},
	{"DEAL FROM HELL", ""},
	{"STUPID DEAL", ""},
	{"MARK OF BEAST", ""},
	{"BEAST TEST", ""},
	{"RECEIVE A MARK", ""},
	{"A ADSX BIO CHIP", ""},
	{"DIGA E-IMPLANT", "(DIGA is the new NASDAQ stock ticker symbol for <a href=https://en.wikipedia.org/wiki/Digi_International>Applied Digital Solutions.</a>"},
	//{"E-TRADE MARKS",""},
	{"E-IDENTITY", ""},
	{"CALCULATION", ""},
	{"WORLD NET", ""},
	{"DIGITAL ID CHIP", ""},
	{"CRYSTAL ID", ""},
	{"SATAN'S RFID", "VeriChip is the first human implantable radio-frequency identification (RFID) microchip approved by the Food and Drug Administration. It is marketed by VeriChip Corporation, a subsidiary of <a href=https://en.wikipedia.org/wiki/Digi_International>Applied Digital Solutions.</a>"},
	{"MONDEX CHIP", ""},
	{"SMART IDOL", ""},
	{"AI SYSTEM", ""},
	{"AI DIGITAL ANGEL", ""},
	{"BIO-IMPLANT", ""},
	{"HE IS ANTI-GOD", "Dan 7:25 Rev 13:5-6"},
	{"NWO DRAGON", "Rev 13:4</a>"},
	{"PART IRON", "Dan 2:41-42</a>"},
	{"SECOND ROME", "Dan 7:7-8 Dan 7:19-26"},
	{"SUPERMEN", "Gen 6:4 Rev 6:15-17"},
	{"AAA BUSINESS", ""},
	{"SKULL-BONE", "Lk 8:17"},
	{"ONE POWER", "Dan 11:38-39"},
	{"STRENGTH", ""},
	{"EARTH SLAVE", "Rev 3:10, 6:10, 8:13, 11:10, 12:12, 13:8, 12, 14, 14:6, 17:8"},
	{"PAY TAXES", ""},
	{"SS NUMBER", ""},
	{"ONE WORLD A.D.", ""},
	{"ONE E-WORLD", ""},
	{"DOUBLESPEAK", "Dan 11:21, Dan 11:32"},
	{"SLAUGHTER", "Rev 11:18"},
	{"A PERDITION", "2 Pet 3:7; Rev 17:8"},
	{"NEW YORK", "Rev 18"},
	{"THE NWO EU", ""},
	{"ILLUSION", "2 Tim 3:7, 13; 2 Thess 2:10-12"},
	{"INSANITY", "2 Tim 3:7, 13; 2 Thess 2:10-12"},
	{"PEOPLE SIN", "Rom 3:23"},
	{"SON OF SIN", "Jn 8:44; Rom 5:12"},
	{"STUBBORN", "1 Sam 15:23"},
	{"HARDENED HEART", "Heb 3:8, 15, 4:7"},
	{"WICKED WILL", "Jer 17:9-10"},
	{"BOOK OF THE DEAD", "Dan 7:9-10; Rev 20:12"},
	{"AN ABSENCE OF GOD", "Eph 2:12"},
	{"IMAGE OF SATAN", "Gen 3:4-5; Isa 14:12-15, 40:19-20; Rev 12:19"},
	{"ABOMINABLE HADES", "Rev 21:8; Hades is Greek for Hell"},
	{"SHEOL: NO END", "Matt 18:8, 25:41; Sheol is Hebrew for Hell"},
	{"DAVID ALLENDER", ""},
	{"FALLING AWAY", "2 Thess 2:3"},
	{"FALLEN CHURCH", "2 Thess 2:3"},
	{"OTHER GODS", "Deut 5:7-9"},
	{"PICTURES", "Num 33:52"},
	{"PAPAL STATE", ""},
	{"CATHOLIC LIAR", "Acts 4:12; 2 Tim 2:5; Ex 20:3-5"},
	{"HINDU'S FIBS", "Deut 5:7-9; Heb 9:27"},
	{"SATAN HINDU", "Isa 8:20"},
	{"BUDDHA FALSIFIED", "Ex 20:4-5; Heb 9:27; Isa 8:20"},
	{"ISLAMIC LIES", "1 Jn 5:7; 2 Tim 2:5; 1 Cor 15:3-4"},
	{"ALLAH WRONG", "Ex 20:3; Isa 8:20"},
	{"SUN MOON", "Deut 17:3"},
	{"CONFUCIUS", ""},
	{"SANTA CLAUS", ""},
	{"ROMAN ANIMAL", "Dan 7:7-8, 23-26, 9:26-27; Rev 13:2, 4-5, 15"},
	{"ODIOUS MAN", "Matt 24:15. Odious: meriting strong dislike. Abominable: detestable or loathsome."},
	{"DEVIL GENE MAN", "John 6:70, 17:12; Acts 1:25; 2 Thess 2:3; Rev 17:8, 11"},
	{"GENETICIST", ""},
	{"A NEW AGE JUDAS", "Gal 1:8-9"},
	{"DRAGON POPE", "Rev 13:11"},
	{"SUICIDE KING", "Rev 14:9-11, 19:20"},
	{"LUCIFER HELL", "Isa 14:12-15"},
	{"LUCIFER HADES", "Hades is Greek for hell"},
	{"DEVIL SHEOL", "Sheol is Hebrew for hell"},
	{"DEVIL DRAGON", "Rev 12:9"},
	//{"GREAT DRAGON",""},
	{"THE DRAGONS", "Ps 74:13: These dragons are fallen angels or devils."},
	{"NAKA FIRE BALLS", ""},
	{"RED FIRE BALLS", ""},
	{"E T WORKS", "Gen 6:1-4; Zech 5:5-11"},
	{"WITCHCRAFT", "Deut 18:10-12"},
	{"NECROMANCY", "Deut 18:10-12"},
	{"SORCERIES", "Rev 9:21"},
	{"SIX TOES", "2 Sam 21:20"},
	{"STAFF LIKE A BEAM", "2 Sam 17:7, 21:19; 1 Chron 20:5"},
}
