package main

type l6 struct {
	str    string
	verses []string
}

var list666 []l6 = []l6{
	{"A SATANIC MARK", []string{}},
	{"SATAN'S SEAL", []string{"Rev 13:16"}},
	{"A SATANIC PLAN", []string{""}},
	{"RECEIVE A MARK", []string{""}},
	{"CHOICE OF DOOM", []string{""}},
	{"FOREHEAD SIGN", []string{"Rev 13:16"}},
	{"THE HAND OR HEAD", []string{"Rev 13:16"}},
	{"EDEN TEMPTED", []string{""}},
	{"PEOPLE SIN", []string{""}},
	{"DEVIL'S HEIR", []string{""}},
	{"HUMANITY", []string{""}},
	{"SON OF SIN", []string{""}},
	{"WICKED WILL", []string{""}},
	{"STUBBORN", []string{""}},
	{"SCORNERS", []string{""}},
	{"LUSTFUL", []string{"1 Jn 2:16-17"}},
	{"TREACHERIES", []string{"Isa 33:1"}},
	{"CORRUPT", []string{"Gen 6:11-12"}},
	{"FLOOD OF NOAH", []string{""}},
	{"COMPUTER", []string{"RAW:The Greek word, \"psephizo,\" translated \"count\" in ", "Rev 13:18", "RAW: is defined as to compute, calculate"}},
	{"TERMINALS", []string{""}},
	{"BIO-IMPLANT", []string{""}},
	{"LUCIFER HELL", []string{""}},
	{"HELL: TWICE DEAD", []string{"Rom 3:23,Jude 11-13,Rev 2:11,Rev 20:6,Rev 14:1,Rev 21:8"}},
	{"HELL: A REAL PLACE", []string{""}},
	{"HELL BURNS", []string{"Lk 16:23-25"}},
	{"SET ON FIRE", []string{""}},
	{"DEAL FROM HELL", []string{""}},
	{"STUPID DEAL", []string{""}},
	{"MARK OF BEAST", []string{""}},
	{"BEAST TEST", []string{""}},
	{"RECEIVE A MARK", []string{""}},
	{"A ADSX BIO CHIP", []string{""}},
	{"DIGA E-IMPLANT", []string{"RAW:DIGA is the new NASDAQ stock ticker symbol for <a href=https://en.wikipedia.org/wiki/Digi_International>Applied Digital Solutions.</a>"}},
	//{"E-TRADE MARKS",[]string{""}},
	{"E-IDENTITY", []string{""}},
	{"CALCULATION", []string{""}},
	{"WORLD NET", []string{""}},
	{"DIGITAL ID CHIP", []string{""}},
	{"CRYSTAL ID", []string{""}},
	{"SATAN'S RFID", []string{"RAW:VeriChip is the first human implantable radio-frequency identification (RFID) microchip approved by the Food and Drug Administration. It is marketed by VeriChip Corporation, a subsidiary of <a href=https://en.wikipedia.org/wiki/Digi_International>Applied Digital Solutions.</a>"}},
	{"MONDEX CHIP", []string{""}},
	{"SMART IDOL", []string{""}},
	{"AI SYSTEM", []string{""}},
	{"AI DIGITAL ANGEL", []string{""}},
	{"BIO-IMPLANT", []string{""}},
	{"HE IS ANTI-GOD", []string{"Dan 7:25,Rev 13:5-6"}},
	{"NWO DRAGON", []string{"Rev 13:4"}},
	{"PART IRON", []string{"Dan 2:41-42"}},
	{"SECOND ROME", []string{"Dan 7:7-8,Dan 7:19-26"}},
	{"SUPERMEN", []string{"Gen 6:4,Rev 6:15-17"}},
	{"AAA BUSINESS", []string{""}},
	{"SKULL-BONE", []string{"Lk 8:17"}},
	{"ONE POWER", []string{"Dan 11:38-39"}},
	{"STRENGTH", []string{""}},
	{"EARTH SLAVE", []string{"Rev 3:10,Rev 6:10,Rev 8:13,Rev 11:10,Rev 12:12,Rev 13:8,Rev 12,Rev 14,Rev 14:6,Rev 17:8"}},
	{"PAY TAXES", []string{""}},
	{"SS NUMBER", []string{""}},
	{"ONE WORLD A.D.", []string{""}},
	{"ONE E-WORLD", []string{""}},
	{"DOUBLESPEAK", []string{"Dan 11:21,Dan 11:32"}},
	{"SLAUGHTER", []string{"Rev 11:18"}},
	{"A PERDITION", []string{"2 Pet 3:7,Rev 17:8"}},
	{"NEW YORK", []string{"Rev 18"}},
	{"THE NWO EU", []string{""}},
	{"ILLUSION", []string{"2 Tim 3:7,2 Tim 3:13,2 Thess 2:10-12"}},
	{"INSANITY", []string{"2 Tim 3:7,2 Tim 3:13,2 Thess 2:10-12"}},
	{"PEOPLE SIN", []string{"Rom 3:23"}},
	{"SON OF SIN", []string{"Jn 8:44,Rom 5:12"}},
	{"STUBBORN", []string{"1 Sam 15:23"}},
	{"HARDENED HEART", []string{"Heb 3:8,Heb 3:15,Heb 4:7"}},
	{"WICKED WILL", []string{"Jer 17:9-10"}},
	{"BOOK OF THE DEAD", []string{"Dan 7:9-10,Rev 20:12"}},
	{"AN ABSENCE OF GOD", []string{"Eph 2:12"}},
	{"IMAGE OF SATAN", []string{"Gen 3:4-5,Isa 14:12-15,Isa 40:19-20,Rev 12:19"}},
	{"ABOMINABLE HADES", []string{"Rev 21:8", "RAW:Hades is Greek for Hell"}},
	{"SHEOL: NO END", []string{"Matt 18:8,Matt 25:41", "RAW:Sheol is Hebrew for Hell"}},
	{"DAVID ALLENDER", []string{""}},
	{"FALLING AWAY", []string{"2 Thess 2:3"}},
	{"FALLEN CHURCH", []string{"2 Thess 2:3"}},
	{"OTHER GODS", []string{"Deut 5:7-9"}},
	{"PICTURES", []string{"Num 33:52"}},
	{"PAPAL STATE", []string{""}},
	{"CATHOLIC LIAR", []string{"Acts 4:12,2 Tim 2:5,Ex 20:3-5"}},
	{"HINDU'S FIBS", []string{"Deut 5:7-9,Heb 9:27"}},
	{"SATAN HINDU", []string{"Isa 8:20"}},
	{"BUDDHA FALSIFIED", []string{"Ex 20:4-5,Heb 9:27,Isa 8:20"}},
	{"ISLAMIC LIES", []string{"1 Jn 5:7,2 Tim 2:5,1 Cor 15:3-4"}},
	{"ALLAH WRONG", []string{"Ex 20:3,Isa 8:20"}},
	{"SUN MOON", []string{"Deut 17:3"}},
	{"CONFUCIUS", []string{""}},
	{"SANTA CLAUS", []string{""}},
	{"ROMAN ANIMAL", []string{"Dan 7:7-8,Dan 7:23-26,Dan 9:26-27,Rev 13:2,Rev 13:4-5,Rev 13:15"}},
	{"ODIOUS MAN", []string{"Matt 24:15", "RAW:Odious: meriting strong dislike. Abominable: detestable or loathsome."}},
	{"DEVIL GENE MAN", []string{"John 6:70,John 17:12,Acts 1:25,2 Thess 2:3,Rev 17:8,Rev 17:11"}},
	{"GENETICIST", []string{""}},
	{"A NEW AGE JUDAS", []string{"Gal 1:8-9"}},
	{"DRAGON POPE", []string{"Rev 13:11"}},
	{"SUICIDE KING", []string{"Rev 14:9-11,Rev 19:20"}},
	{"LUCIFER HELL", []string{"Isa 14:12-15"}},
	{"LUCIFER HADES", []string{"RAW:Hades is Greek for hell"}},
	{"DEVIL SHEOL", []string{"RAW:Sheol is Hebrew for hell"}},
	{"DEVIL DRAGON", []string{"Rev 12:9"}},
	//{"GREAT DRAGON",[]string{""}},
	{"THE DRAGONS", []string{"Ps 74:13", "RAW: These dragons are fallen angels or devils."}},
	{"NAKA FIRE BALLS", []string{""}},
	{"RED FIRE BALLS", []string{""}},
	{"E T WORKS", []string{"Gen 6:1-4,Zech 5:5-11"}},
	{"WITCHCRAFT", []string{"Deut 18:10-12"}},
	{"NECROMANCY", []string{"Deut 18:10-12"}},
	{"SORCERIES", []string{"Rev 9:21"}},
	{"SIX TOES", []string{"2 Sam 21:20"}},
	{"STAFF LIKE A BEAM", []string{"2 Sam 17:7,2 Sam 21:19,1 Chron 20:5"}},
}
