package main

type l6 struct {
	str   string
	verse string
}

var list666 []l6 = []l6{
	{"A SATANIC MARK", ""},
	{"SATAN'S SEAL", "<a href=https://www.biblegateway.com/passage/?search=Revelation%2013%3A16-17&version=KJV>Rev 13:16</a>"},
	{"A SATANIC PLAN", ""},
	{"RECEIVE A MARK", ""},
	{"CHOICE OF DOOM", ""},
	{"FOREHEAD SIGN", "<a href=https://www.biblegateway.com/passage/?search=Revelation%2013%3A16-17&version=KJV>Rev 13:16</a>"},
	{"THE HAND OR HEAD", "<a href=https://www.biblegateway.com/passage/?search=Revelation%2013%3A16-17&version=KJV>Rev 13:16</a>"},
	{"EDEN TEMPTED", ""},
	{"PEOPLE SIN", ""},
	{"DEVIL'S HEIR", ""},
	{"HUMANITY", ""},
	{"SON OF SIN", ""},
	{"WICKED WILL", ""},
	{"STUBBORN", ""},
	{"SCORNERS", ""},
	{"LUSTFUL", ""},
	{"TREACHERIES", ""},
	{"CORRUPT", ""},
	{"FLOOD OF NOAH", ""},
	{"COMPUTER", "The Greek word, \"psephizo,\" translated \"count\" in <a href=https://www.biblegateway.com/passage/?search=Revelation%2013%3A18&version=KJV>Rev 13:18</a> is defined as to compute, calculate"},
	{"TERMINALS", ""},
	{"BIO-IMPLANT", ""},
	{"LUCIFER HELL", ""},
	{"HELL: TWICE DEAD", ""},
	{"HELL: A REAL PLACE", ""},
	{"HELL BURNS", ""},
	{"SET ON FIRE", ""},
	{"DEAL FROM HELL", ""},
	{"STUPID DEAL", ""},
	{"MARK OF BEAST", ""},
	{"BEAST TEST", ""},
	{"RECEIVE A MARK", ""},
	{"A ADSX BIO CHIP", ""},
	{"DIGA E-IMPLANT", ""},
	//{"E-TRADE MARKS",""},
	{"E-IDENTITY", ""},
	{"CALCULATION", ""},
	{"WORLD NET", ""},
	{"DIGITAL ID CHIP", ""},
	{"CRYSTAL ID", ""},
	{"SATAN'S RFID", ""},
	{"MONDEX CHIP", ""},
	{"SMART IDOL", ""},
	{"AI SYSTEM", ""},
	{"AI DIGITAL ANGEL", ""},
	{"BIO-IMPLANT", ""},
	{"HE IS ANTI-GOD", ""},
	{"NWO DRAGON", ""},
	{"PART IRON", ""},
	{"SECOND ROME", ""},
	{"SUPERMEN", ""},
	{"AAA BUSINESS", ""},
	{"SKULL-BONE", ""},
	{"ONE POWER", ""},
	{"STRENGTH", ""},
	{"EARTH SLAVE", ""},
	{"PAY TAXES", ""},
	{"SS NUMBER", ""},
	{"ONE WORLD A.D.", ""},
	{"ONE E-WORLD", ""},
	{"DOUBLESPEAK", ""},
	{"SLAUGHTER", ""},
	{"A PERDITION", ""},
	{"NEW YORK", ""},
	{"THE NWO EU", ""},
	{"ILLUSION", ""},
	{"INSANITY", ""},
	{"PEOPLE SIN", ""},
	{"SON OF SIN", ""},
	{"STUBBORN", ""},
	{"HARDENED HEART", ""},
	{"STUBBORN", ""},
	{"HARDENED HEART", ""},
	{"WICKED WILL", ""},
	{"BOOK OF THE DEAD", ""},
	{"AN ABSENCE OF GOD", ""},
	{"IMAGE OF SATAN", ""},
	{"ABOMINABLE HADES", ""},
	{"SHEOL: NO END", ""},
	{"DAVID ALLENDER", ""},
	{"FALLING AWAY", ""},
	{"FALLEN CHURCH", ""},
	{"OTHER GODS", ""},
	{"PICTURES", ""},
	{"PAPAL STATE", ""},
	{"CATHOLIC LIAR", ""},
	{"HINDU'S FIBS", ""},
	{"SATAN HINDU", ""},
	{"BUDDHA FALSIFIED", ""},
	{"ISLAMIC LIES", ""},
	{"ALLAH WRONG", ""},
	{"SUN MOON", ""},
	{"CONFUCIUS", ""},
	{"SANTA CLAUS", ""},
	{"ROMAN ANIMAL", ""},
	{"ODIOUS MAN", ""},
	{"DEVIL GENE MAN", ""},
	{"GENETICIST", ""},
	{"A NEW AGE JUDAS", ""},
	{"DRAGON POPE", ""},
	{"SUICIDE KING", ""},
	{"LUCIFER HELL", ""},
	{"LUCIFER HADES", ""},
	{"DEVIL SHEOL", ""},
	{"DEVIL DRAGON", ""},
	//{"GREAT DRAGON",""},
	{"THE DRAGONS", ""},
	{"NAKA FIRE BALLS", ""},
	{"RED FIRE BALLS", ""},
	{"E T WORKS", ""},
	{"WITCHCRAFT", ""},
	{"NECROMANCY", ""},
	{"SORCERIES", ""},
	{"SIX TOES", ""},
	{"STAFF LIKE A BEAM", ""},
}
