package main

type l8 struct {
	str   string
	verse string
}

var list888 []l8 = []l8{
	{"GEMATRIA: CODE OF GOD", "test"},
	{"ENGLISH GEMATRIA", ""},
	{"SIMPLE ENGLISH", ""},
	//{"LANGUAGE MIRACLE",""},
	{"ANTICHRIST CODE", ""},
	{"GOD'S NUMBERING", ""},
	{"THE TRINITY", ""},
	{"MESSIAH JESUS", ""},
	{"THE LION OF JUDAH", ""},
	{"MORNING STAR", ""},
	{"THE KING JESUS", ""},
	{"FINISHED CROSS", ""},
	{"DIVINE PRESENCE", ""},
	{"OMNIPRESENT", ""},
	{"THE LORD'S TIME", ""},
	{"COMING TRUTH", ""},
	{"KING OF THE SABBATH", ""},
	{"BIBLICAL PROPHET", ""},
	{"THE HOUSE OF GOD", ""},
	{"LAW OF LIBERTY", ""},
	{"SCRIPTURES", ""},
	{"THE PASSOVER", ""},
	{"LAMB OF GOD SACRIFICE", ""},
	{"LIVE IN CHRIST", ""},
	{"SAVED IN JESUS", ""},
	{"JESUS FORGAVE", ""},
	{"CHRIST RECEIVED", ""},
	{"SPIRIT BIRTH", ""},
	{"JESUS' GOSPEL", ""},
	{"RIGHTEOUS GOD", ""},
	{"SAVED IN JESUS", ""},
	{"JESUS' CROSS", ""},
	{"SPIRIT BIRTH", ""},
	{"GOD'S ANOINTING", ""},
	{"NEBUCHADNEZZAR", ""},
	{"JESUS' CHURCH AGE", ""},
	{"THE HOUSE OF GOD", ""},
	{"BAPTIST CHURCH", ""},
	{"ONE ALMIGHTY JAH", ""},
	{"JEWISH MESSIAH", ""},
	{"OBEDIENT MESSIAH", ""},
	{"THE KING JESUS", ""},
	{"A HOLY TRUTH", ""},
	{"HE THAT WAITETH", ""},
	{"PROPHECY ENDS", ""},
	{"GOD'S PERFECT BIBLE", ""},
	{"LAW OF LIBERTY", ""},
	{"GOD'S WORD: KJV", ""},
	{"THE SWORD LAW", ""},
	{"OLD TESTAMENT", ""},
	{"THE LIVE WATER", ""},
	{"WASHING WATER", ""},
}
