package main

type l8 struct {
	str    string
	verses []string
}

var list888 []l8 = []l8{
	{"MESSIAH JESUS", []string{"RAW:The Lord's name,JESUS,in Koine Greek totals 888"}},
	{"GEMATRIA: CODE OF GOD", []string{""}},
	{"ENGLISH GEMATRIA", []string{""}},
	{"SIMPLE ENGLISH", []string{""}},
	//{"LANGUAGE MIRACLE",""},
	{"ANTICHRIST CODE", []string{""}},
	{"GOD'S NUMBERING", []string{""}},
	{"THE TRINITY", []string{"Jn 5:7"}},
	{"THE LION OF JUDAH", []string{"Rev 5:5"}},
	{"MORNING STAR", []string{"Rev 22:16"}},
	{"THE KING JESUS", []string{""}},
	{"FINISHED CROSS", []string{"Jn 19:30"}},
	{"DIVINE PRESENCE", []string{""}},
	{"OMNIPRESENT", []string{""}},
	{"THE LORD'S TIME", []string{""}},
	{"COMING TRUTH", []string{"Jn 14:1-6"}},
	{"KING OF THE SABBATH", []string{"Matt 12:8"}},
	{"BIBLICAL PROPHET", []string{"Deut 18:15,Acts 3:19-23"}},
	{"THE HOUSE OF GOD", []string{""}},
	{"LAW OF LIBERTY", []string{""}},
	{"SCRIPTURES", []string{""}},
	{"THE PASSOVER", []string{""}},
	{"LAMB OF GOD SACRIFICE", []string{""}},
	{"LIVE IN CHRIST", []string{""}},
	{"SAVED IN JESUS", []string{""}},
	{"JESUS FORGAVE", []string{"Lk 23:34"}},
	{"CHRIST RECEIVED", []string{""}},
	{"SPIRIT BIRTH", []string{"Jn 3:5-8,Rev 21:6,Rev 22:17"}},
	{"JESUS' GOSPEL", []string{"Mark 1:1,Mark 1:14-15"}},
	{"RIGHTEOUS GOD", []string{"Ps 7:9"}},
	{"SAVED IN JESUS", []string{"2 Tim 1:9"}},
	{"JESUS' CROSS", []string{"Jn 19:19,Heb 12:2,Gal 6:14"}},
	{"SPIRIT BIRTH", []string{""}},
	{"GOD'S ANOINTING", []string{"1 Jn 2:27"}},
	{"NEBUCHADNEZZAR", []string{"Dan 4:34-37"}},
	{"JESUS' CHURCH AGE", []string{""}},
	{"THE HOUSE OF GOD", []string{""}},
	{"BAPTIST CHURCH", []string{""}},
	{"ONE ALMIGHTY JAH", []string{"Ps 68:4,1 Jn 5:7,Rev 1:8"}},
	{"JEWISH MESSIAH", []string{"Dan 9:24-26"}},
	{"OBEDIENT MESSIAH", []string{"Phil 2:6-8"}},
	{"THE KING JESUS", []string{"Jn 18:37,1 Tim 6:15,Rev 17:14,Rev:19:16"}},
	{"A HOLY TRUTH", []string{"Acts 4:26-28"}},
	{"HE THAT WAITETH", []string{"Prov 27:18,Ps 33:20,62:1,Isa 64:4,Dan 12:12"}},
	{"PROPHECY ENDS", []string{"1 Cor 13:8-12,Jude 3"}},
	{"GOD'S PERFECT BIBLE", []string{"Jam 1:25,Ps 19:7"}},
	{"LAW OF LIBERTY", []string{"Jam 1:25,2:12"}},
	{"GOD'S WORD: KJV", []string{"Ps 12:6-7"}},
	{"THE SWORD LAW", []string{"Jam 1:25,2:12"}},
	{"OLD TESTAMENT", []string{"2 Cor 3:14-16"}},
	{"THE LIVE WATER", []string{"Eph 5:26,Jn 3:5,4:10,13:3-11,17:17,Isa 55:10-11"}},
	{"WASHING WATER", []string{"Jn 3:5,Eph 5:26,Titus 3:5,1 Jn 5:6-8,Rev 21:6,Rev 22:17"}},
}
